# Generated by Django 5.2.5 on 2025-08-14 06:21

import django.db.models.deletion
import tinymce.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Advertisement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ads', models.ImageField(upload_to='ads')),
                ('adsAlt', models.CharField(max_length=60)),
                ('adsUrl', models.CharField(max_length=260)),
                ('adsUploadDate', models.DateField()),
                ('adsEndingDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Basement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('slug', models.CharField(max_length=30, unique=True)),
                ('content', tinymce.models.HTMLField()),
                ('strip', models.TextField()),
                ('seo', models.TextField()),
                ('advertisement', models.ManyToManyField(to='mama.advertisement')),
            ],
        ),
        migrations.CreateModel(
            name='Counselor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('position', models.CharField(max_length=60)),
                ('phoneNumber', models.CharField(max_length=20)),
                ('buttonDisplay', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('favicon', models.ImageField(upload_to='')),
                ('facebook', models.CharField(max_length=120)),
                ('quote', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Storage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=60)),
                ('file', models.FileField(upload_to='file')),
                ('uploadDate', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254)),
                ('phoneNumber', models.CharField(max_length=16)),
                ('collegeName', models.CharField(max_length=30)),
                ('status', models.CharField(max_length=10)),
                ('cunselor', models.CharField(choices=[('In Process', 'In Process'), ('Not Intrested', 'Not Intrested'), ('Pending', 'Pending'), ('Completed', 'Completed')], default='Mama Shree', editable=False)),
                ('note', models.TextField()),
                ('createdDate', models.DateTimeField(auto_now_add=True)),
                ('updatedDate', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('date', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Article',
            fields=[
                ('basement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mama.basement')),
            ],
            bases=('mama.basement',),
        ),
        migrations.CreateModel(
            name='Scheme',
            fields=[
                ('basement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mama.basement')),
            ],
            bases=('mama.basement',),
        ),
        migrations.CreateModel(
            name='Scholarship',
            fields=[
                ('basement_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='mama.basement')),
            ],
            bases=('mama.basement',),
        ),
    ]
