# Generated by Django 5.2.5 on 2025-08-14 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': 'Article', 'verbose_name_plural': 'Articles'},
        ),
        migrations.AlterModelOptions(
            name='scheme',
            options={'verbose_name': 'Scheme', 'verbose_name_plural': 'Scheme'},
        ),
        migrations.AlterModelOptions(
            name='scholarship',
            options={'verbose_name': 'Scholarship', 'verbose_name_plural': 'Scholarships'},
        ),
        migrations.AlterField(
            model_name='basement',
            name='advertisement',
            field=models.ManyToManyField(blank=True, to='mama.advertisement'),
        ),
        migrations.AlterField(
            model_name='basement',
            name='strip',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='collegeName',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='student',
            name='cunselor',
            field=models.CharField(default='Mama Shree', editable=False),
        ),
        migrations.AlterField(
            model_name='student',
            name='note',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='student',
            name='status',
            field=models.CharField(blank=True, max_length=12),
        ),
    ]
