# Generated by Django 5.2.5 on 2025-08-14 17:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0002_alter_article_options_alter_scheme_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='counselor',
            options={'verbose_name': 'Counselor', 'verbose_name_plural': 'Counselor'},
        ),
        migrations.AddField(
            model_name='basement',
            name='active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='basement',
            name='createdDate',
            field=models.DateField(auto_now_add=True, default=datetime.date(2025, 8, 14)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='basement',
            name='updatedDate',
            field=models.DateField(auto_now=True),
        ),
    ]
