# Generated by Django 5.2.5 on 2025-08-15 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0003_alter_counselor_options_basement_active_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='storage',
            options={'verbose_name': 'Storage', 'verbose_name_plural': 'Storage'},
        ),
        migrations.AddField(
            model_name='advertisement',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
