# Generated by Django 5.2.5 on 2025-08-15 04:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0004_alter_storage_options_advertisement_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='advertisement',
            old_name='ads',
            new_name='adsImage',
        ),
    ]
