# Generated by Django 5.2.5 on 2025-08-15 05:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0005_rename_ads_advertisement_adsimage'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='counselor',
            name='buttonDisplay',
        ),
    ]
