# Generated by Django 5.2.5 on 2025-08-16 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0006_remove_counselor_buttondisplay'),
    ]

    operations = [
        migrations.AddField(
            model_name='storage',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
