# Generated by Django 5.2.5 on 2025-08-16 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mama', '0007_storage_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storage',
            name='title',
            field=models.CharField(max_length=260),
        ),
    ]
